// <auto-generated />
using System;
using JobHunt.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace JobHunt.Infrastructure.Migrations
{
    [DbContext(typeof(JobHuntDbContext))]
    [Migration("20241123141140_adding profile_summary and specialization columns to profile table")]
    partial class addingprofile_summaryandspecializationcolumnstoprofiletable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("JobHunt.Domain.Models.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("addresses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0ca4032a-b0c0-4d25-8575-f5b065d7df54"),
                            City = "Warsaw",
                            Country = "Poland",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Street = "Krakowskie Przedmieście 10",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("525c49eb-3406-4210-9125-6085e59b4eb3"),
                            City = "Kraków",
                            Country = "Poland",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Street = "Floriańska 15",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("81829923-f40e-4f58-9506-08da478058a2"),
                            City = "Gdańsk",
                            Country = "Poland",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Street = "Dluga 20",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("760b41f0-1ae8-4140-aeaa-c51edb8524dd"),
                            City = "Wrocław",
                            Country = "Poland",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Street = "Rynek 5",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("65997657-6342-4461-991e-d9ef4cc27808"),
                            City = "Poznań",
                            Country = "Poland",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Street = "Święty Marcin 45",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("c4d716dc-e536-4f93-affd-1eca9be155f1"),
                            City = "Łódź",
                            Country = "Poland",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Street = "Piotrkowska 31",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("02cb7c97-8ac4-4df1-b9bb-a9ff6732c728"),
                            City = "Lublin",
                            Country = "Poland",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Street = "Krakowskie Przedmieście 2",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("eb0bf179-2a90-42f2-a778-0457f10280b7"),
                            City = "Katowice",
                            Country = "Poland",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Street = "3 Maja 9",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6dceaa73-c28e-4aa5-b148-aa673e9b80b5"),
                            City = "Bydgoszcz",
                            Country = "Poland",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Street = "Gdańska 14",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("aecc1bcc-91a9-406c-9258-b38bbd12fdb9"),
                            City = "Szczecin",
                            Country = "Poland",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Street = "Aleja Wyzwolenia 21",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("61e53104-cc1e-4403-b781-ac2a9d90a675"),
                            City = "Gdynia",
                            Country = "Poland",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Street = "Świętojańska 6",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d1977ab7-eef3-4def-ae48-66f65922b471"),
                            City = "Toruń",
                            Country = "Poland",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Street = "Rynek Staromiejski 3",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a538082d-1000-4b50-b6ea-7e0f8b715c14"),
                            City = "Opole",
                            Country = "Poland",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Street = "Krakowska 7",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("bc05e016-1537-41f6-80b3-9bbf991dd39c"),
                            City = "Rzeszów",
                            Country = "Poland",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Street = "3 Maja 12",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("3a55e504-11f1-4c82-8628-692982996558"),
                            City = "Białystok",
                            Country = "Poland",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Street = "Lipowa 15",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9c654eec-ba66-40a6-8bf7-160591a9a602"),
                            City = "Zielona Góra",
                            Country = "Poland",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Street = "Bohaterów Westerplatte 10",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("5f6ec67a-de91-4260-a1cf-50aebeb8181b"),
                            City = "Gliwice",
                            Country = "Poland",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Street = "Zwycięstwa 22",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("6270749d-0b30-4e83-8374-12d23c22271a"),
                            City = "Sopot",
                            Country = "Poland",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Street = "Monte Cassino 25",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("868f8731-4a07-44fd-bd27-4acb4a35f77f"),
                            City = "Koszalin",
                            Country = "Poland",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Street = "Zwycięstwa 5",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4b23304a-d75c-4dff-8b86-402a8656f39c"),
                            City = "Radom",
                            Country = "Poland",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Street = "Żeromskiego 16",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("JobHunt.Domain.Models.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("position");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("Responsibility")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("responsibility");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateOnly>("WorkFrom")
                        .HasColumnType("date")
                        .HasColumnName("work_from");

                    b.Property<DateOnly>("WorkTo")
                        .HasColumnType("date")
                        .HasColumnName("work_to");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("experiences", (string)null);
                });

            modelBuilder.Entity("JobHunt.Domain.Models.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("images", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b7a18197-c6d6-47c4-ab72-d3a042b646c3"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://jobhuntstorage.blob.core.windows.net/images/jfd.jpg",
                            Name = "jfd.jpg",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("47219591-466c-4f33-bd2e-4b165844b4da"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://jobhuntstorage.blob.core.windows.net/images/mfd.jpg",
                            Name = "mfd.jpg",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9788b6d6-2dfd-4272-8249-43a66bfc5e2b"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://jobhuntstorage.blob.core.windows.net/images/sfd.png",
                            Name = "sfd.png",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("fc8e5936-d76a-4d3a-bc64-d91d6d6e7da9"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://jobhuntstorage.blob.core.windows.net/images/lfd.png",
                            Name = "lfd.png",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7d296ead-d7f2-4f9d-a2d9-f756b0aaa1a4"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://jobhuntstorage.blob.core.windows.net/images/jbd.jpg",
                            Name = "jbd.jpg",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("5f890acc-9532-4c56-9e3c-07a45a91dc83"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://jobhuntstorage.blob.core.windows.net/images/mbd.jpg",
                            Name = "mbd.jpg",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("239b185c-4d37-4b01-baba-001b4425794a"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://jobhuntstorage.blob.core.windows.net/images/sbd.png",
                            Name = "sbd.png",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("caa67e3a-d380-4a7f-9921-bce41d768349"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://jobhuntstorage.blob.core.windows.net/images/lbd.png",
                            Name = "lbd.png",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ba1c1bbf-cd15-49ce-8fcb-d744593c5299"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://jobhuntstorage.blob.core.windows.net/images/jfld.png",
                            Name = "jfld.png",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("0c97833d-79fb-43d9-a1e1-25032d81ad77"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://jobhuntstorage.blob.core.windows.net/images/mfld.png",
                            Name = "mfld.png",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f884c7f8-502a-49a6-acde-7350a412b097"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://jobhuntstorage.blob.core.windows.net/images/sfld.png",
                            Name = "sfld.png",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("01761843-a4d3-4dbd-988b-977094f0a083"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://jobhuntstorage.blob.core.windows.net/images/lfld.png",
                            Name = "lfld.png",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("32bafe62-e9ba-4c2a-9f2a-76053c689eff"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://jobhuntstorage.blob.core.windows.net/images/jgd.jpg",
                            Name = "jgd.jpg",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a7bcaf46-c806-4bf4-825f-e17852cd276c"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://jobhuntstorage.blob.core.windows.net/images/mgd.jpg",
                            Name = "mgd.jpg",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("20deaa5a-9243-4e3d-bed1-dc0a23aaccd3"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://jobhuntstorage.blob.core.windows.net/images/sgd.jpg",
                            Name = "sgd.jpg",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d86c3bf1-22f9-467a-bb25-a335508074c2"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://jobhuntstorage.blob.core.windows.net/images/lgd.png",
                            Name = "lgd.png",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("39fd3f9a-1911-4676-b4cf-d245f68a83a7"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://jobhuntstorage.blob.core.windows.net/images/jmd.png",
                            Name = "jmd.png",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ba513f10-c72d-4cdb-a105-d6b462ec61fe"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://jobhuntstorage.blob.core.windows.net/images/mmd.png",
                            Name = "mmd.png",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("8b9cea71-52d1-46fd-b1e7-b2b54726bfa6"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://jobhuntstorage.blob.core.windows.net/images/smd.jpg",
                            Name = "smd.jpg",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("aa697543-3225-4e7b-8baf-83d71683b2c8"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImageUrl = "https://jobhuntstorage.blob.core.windows.net/images/lmd.png",
                            Name = "lmd.png",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("JobHunt.Domain.Models.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AboutCompany")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("about_company");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid")
                        .HasColumnName("address_id");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<string>("ContractType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contract_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_id");

                    b.Property<string>("JobLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("job_level");

                    b.Property<string>("OperationMode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("operation_mode");

                    b.Property<string>("Requirements")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requirements");

                    b.Property<string>("Responsibilities")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("responsibilities");

                    b.Property<string>("Salary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("salary");

                    b.Property<string>("Technology")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("technology");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("ImageId")
                        .IsUnique();

                    b.HasIndex("Title", "JobLevel", "Technology", "Type")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Title", "JobLevel", "Technology", "Type"), "GIN");

                    b.ToTable("jobs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("6b6b9d9a-1816-4218-b346-e106f37ef2b3"),
                            AboutCompany = "Web and mobile dev",
                            AddressId = new Guid("81829923-f40e-4f58-9506-08da478058a2"),
                            CompanyName = "Code Factory",
                            ContractType = "UOP",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "f948c6b6-2651-4cf5-a4ae-a2046511989d",
                            ImageId = new Guid("b7a18197-c6d6-47c4-ab72-d3a042b646c3"),
                            JobLevel = "Junior",
                            OperationMode = "Remote",
                            Requirements = "[\"Wykszta\\u0142cenie: min. student 3 roku - kierunek informatyka lub pokrewny\",\"Znajomo\\u015B\\u0107: Vue 3 \\u002B Angular \\u002B CSS \\u002B TypeScript\",\"Znajomo\\u015B\\u0107 system\\u00F3w kontroli wersji (Git)\",\"Znajomo\\u015B\\u0107 j\\u0119zyka angielskiego umo\\u017Cliwiaj\\u0105ca sprawn\\u0105 komunikacj\\u0119 w mowie i w pi\\u015Bmie\"]",
                            Responsibilities = "[\"Projektowanie i implementowanie Front-endu na podstawie wymaga\\u0144 biznesowych\",\"Testowanie manualne oraz automatyczne dostarczanych rozwi\\u0105za\\u0144\",\"Udzia\\u0142 w pracach utrzymaniowych w \\u015Brodowiskach testowych i produkcyjnych\"]",
                            Salary = "4000-5000 zł brutto",
                            Technology = "Js",
                            Title = "Junior Frontend Developer",
                            Type = "Frontend",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9e036ded-241a-43b8-b1e4-c6b091d8c599"),
                            AboutCompany = "Web innovation leaders",
                            AddressId = new Guid("760b41f0-1ae8-4140-aeaa-c51edb8524dd"),
                            CompanyName = "Web Wonders",
                            ContractType = "UOP",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "f948c6b6-2651-4cf5-a4ae-a2046511989d",
                            ImageId = new Guid("47219591-466c-4f33-bd2e-4b165844b4da"),
                            JobLevel = "Middle",
                            OperationMode = "Hybrid",
                            Requirements = "[\"3-4 years of experience in frontend development using Angular and TypeScript.\",\"Additional proficiency with Lit, Sass, Java, C\\u002B\\u002B is preferred.\",\"Openness to contributing to Google\\u0027s future success in Cloud AI.\",\"English level: min B2\\u002B.\"]",
                            Responsibilities = "[\"Build user interfaces using Angular and TypeScript for Google Cloud\\u0027s AI applications.\",\"Work closely with backend teams, PM, UX Researchers, and UX Designers on improvements to Cloud AI products.\",\"Design and build new frontend components and features for all Cloud AI applications and services.\",\"Opportunities to work on end-to-end features including UI, API and backend layers to develop full-stack experience.\"]",
                            Salary = "6000-8000 zł brutto",
                            Technology = "Typescript",
                            Title = "Middle Frontend Developer",
                            Type = "Frontend",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("147b66ef-0888-4c17-8663-bec7a4bd4d99"),
                            AboutCompany = "Leading in AI solutions",
                            AddressId = new Guid("0ca4032a-b0c0-4d25-8575-f5b065d7df54"),
                            CompanyName = "Tech Innovators",
                            ContractType = "B2B",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "f948c6b6-2651-4cf5-a4ae-a2046511989d",
                            ImageId = new Guid("9788b6d6-2dfd-4272-8249-43a66bfc5e2b"),
                            JobLevel = "Senior",
                            OperationMode = "Remote",
                            Requirements = "[\"7\\u002B years of experience\",\"Expert experience with HTML, CSS, React, and Node.js\",\"High fidelity HTML/CSS prototyping skills\",\"Excellent knowledge of design systems and responsive web design\",\"Strong understanding of component-based development within a shared style guide context\",\"Deep knowledge of web accessibility standards\",\"Expertise in managing cross-browser issues \"]",
                            Responsibilities = "[\"Collaborating with a cross-functional team of UX designers and UI developers\",\"Iteratively coding with considerations for fast-paced delivery and quality\",\"Working with multiple stakeholders including product owners and engineering leads\",\"Developing and maintaining a consistent approach to our component library and consuming applications\",\"Mentoring junior team members\",\"Ensuring UI consistency across multiple applications in collaboration with engineering leadership\",\"Adhering to best practices in our UX/UI functions\",\"Creating high-fidelity HTML/CSS prototypes\",\"Addressing cross-browser concerns and ensuring web accessibility\"]",
                            Salary = "10000-12000 zł netto",
                            Technology = "React",
                            Title = "Senior Frontend Developer",
                            Type = "Frontend",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("1299cc56-179c-4c92-a00e-3661f6e9def9"),
                            AboutCompany = "Web dev specialists",
                            AddressId = new Guid("525c49eb-3406-4210-9125-6085e59b4eb3"),
                            CompanyName = "WebWorks",
                            ContractType = "B2B",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "f948c6b6-2651-4cf5-a4ae-a2046511989d",
                            ImageId = new Guid("fc8e5936-d76a-4d3a-bc64-d91d6d6e7da9"),
                            JobLevel = "Lead",
                            OperationMode = "Hybrid",
                            Requirements = "[\"Strong proficiency in React for building dynamic, component-driven user interfaces\",\"In-depth knowledge of Redux for state management, including actions, reducers, and middlewares (such as Redux Thunk or Redux Saga)\",\"Experience with React hooks (useEffect, useState, etc.) and functional components\",\"Proficiency in JavaScript (ES6\\u002B)\",\"Familiarity with React Router for navigation and Axios for API requests\",\"Understanding of CSS\"]",
                            Responsibilities = "[\"Working in international Scrum Team to deliver Business critical solutions within the terminal/transit warehousing area in close cooperation with Product Owner\",\"Developing and technically owning backend (Java 17\\u002B/Spring, Event-Driven Architecture) and frontend (React for building dynamic, component-driven user interfaces) applications hosted in Azure Cloud\",\"Continuous improvement of products and internal delivery \\u0026 maintenance processes\"]",
                            Salary = "15000-20000 zł netto",
                            Technology = "Js",
                            Title = "Lead Frontend Engineer",
                            Type = "Frontend",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e4b7238c-9aec-4d63-80bb-514be1dc70a2"),
                            AboutCompany = "Focus on data analytics",
                            AddressId = new Guid("65997657-6342-4461-991e-d9ef4cc27808"),
                            CompanyName = "DataX Solutions",
                            ContractType = "B2B",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c5bb0f28-a52d-4c3a-9fec-6e7eb50da633",
                            ImageId = new Guid("7d296ead-d7f2-4f9d-a2d9-f756b0aaa1a4"),
                            JobLevel = "Junior",
                            OperationMode = "Hybrid",
                            Requirements = "[\"Do\\u015Bwiadczenie w programowaniu z wykorzystaniem C# .Net\",\"Znajomo\\u015B\\u0107 Microsoft SQL Server w zakresie tworzenia zapyta\\u0144\",\"Do\\u015Bwiadczenie w projektowaniu lub tworzeniu aplikacji komercyjnych (mile widziane)\",\"Znajomo\\u015B\\u0107 j\\u0119z. angielskiego umo\\u017Cliwiaj\\u0105ca czytanie dokumentacji technicznej\"]",
                            Responsibilities = "[\"Assist backend development team\",\"Szukamy osoby, kt\\u00F3rej zadaniem b\\u0119dzie rozwijanie naszego produktu opartego o \\u015Brodowisko bazodanowe MS SQL oraz .Net\"]",
                            Salary = "5000-6000 zł netto",
                            Technology = ".Net",
                            Title = "Junior Backend Developer",
                            Type = "Backend",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("d4f5edd1-e1bf-4f67-908d-f69c014e975d"),
                            AboutCompany = "Data science leaders",
                            AddressId = new Guid("02cb7c97-8ac4-4df1-b9bb-a9ff6732c728"),
                            CompanyName = "DataScience Co",
                            ContractType = "UOP",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c5bb0f28-a52d-4c3a-9fec-6e7eb50da633",
                            ImageId = new Guid("5f890acc-9532-4c56-9e3c-07a45a91dc83"),
                            JobLevel = "Middle",
                            OperationMode = "Remote",
                            Requirements = "[\"3\\u002B years with Python, Flask\",\"do\\u015Bwiadczenie na stanowisku programisty \\u2013 minimum 2 lata;\",\"do\\u015Bwiadczenie w pracy projektowej w zespole deweloperskim;\",\"dobra znajomo\\u015B\\u0107 wzorc\\u00F3w projektowych, zasad programowania obiektowego;\",\"znajomo\\u015B\\u0107 narz\\u0119dzi kontroli wersji Git;\",\"do\\u015Bwiadczenie w pisaniu test\\u00F3w jednostkowych, integracyjnych;\",\"samodzielno\\u015B\\u0107 i komunikatywno\\u015B\\u0107.\"]",
                            Responsibilities = "[\"projektowanie i implementacja rozwi\\u0105za\\u0144 informatycznych;\",\"praca w oparciu o zwinn\\u0105 metodyk\\u0119 wytwarzania oprogramowania;\",\"dbanie o jako\\u015B\\u0107 kodu \\u017Ar\\u00F3d\\u0142owego;\",\"wsp\\u00F3\\u0142praca z pozosta\\u0142ymi cz\\u0142onkami zespo\\u0142u.\"]",
                            Salary = "7000-9000 zł brutto",
                            Technology = "Python",
                            Title = "Middle Backend Developer",
                            Type = "Backend",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("15c479dd-5da6-4329-af99-c0b16d0cc265"),
                            AboutCompany = "Experts in cloud tech",
                            AddressId = new Guid("c4d716dc-e536-4f93-affd-1eca9be155f1"),
                            CompanyName = "Cloudify",
                            ContractType = "B2B",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c5bb0f28-a52d-4c3a-9fec-6e7eb50da633",
                            ImageId = new Guid("239b185c-4d37-4b01-baba-001b4425794a"),
                            JobLevel = "Senior",
                            OperationMode = "Remote",
                            Requirements = "[\" Minimum 3-letnie do\\u015Bwiadczenie w budowaniu aplikacji pythonowych\",\" Do\\u015Bwiadczenie w projektowaniu i budowaniu wysoko-skalowalnych aplikacji z r\\u00F3wnoleg\\u0142ym strumieniem przetwarzania\",\" Tworzenie czytelnego kodu zgodnego z zasadami SOLID, umiej\\u0119tno\\u015B\\u0107 wykorzystywania Design Patterns w codziennej pracy\",\" Podstawowa znajomo\\u015B\\u0107 algorytm\\u00F3w i struktur danych\",\" J\\u0119zyk angielski na poziomie umo\\u017Cliwiaj\\u0105cym swobodne czytanie i pisanie dokumentacji oraz porozumiewanie si\\u0119 z wsp\\u00F3\\u0142pracownikami (min. B2)\",\" Do\\u015Bwiadczenie w pracy z JavaScript, optymalnie NestJS\",\"Do\\u015Bwiadczenie w pracy z Flask oraz relacyjnymi i nie relacyjnymi bazami danych\",\" Znajomo\\u015B\\u0107 ekosystemu AWS\"]",
                            Responsibilities = "[\" Wsparcie zespo\\u0142u w budowaniu architektury aplikacji\",\" Udzia\\u0142 w podejmowaniu decyzji i rozwi\\u0105zywaniu problem\\u00F3w w okre\\u015Blonych obszarach projektu\",\"Wsparcie prowadzenia zespo\\u0142u developerskiego\",\"  Dzielenie si\\u0119 wiedz\\u0105 i do\\u015Bwiadczeniami z reszt\\u0105 zespo\\u0142u\",\" Pisanie czystego, wydajnego kodu\",\" Prowadzenie procesu Code Review oraz podejmowanie decyzji na poziomie kodu\"]",
                            Salary = "12000-15000 zł netto",
                            Technology = "Python",
                            Title = "Senior Backend Engineer",
                            Type = "Backend",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("2efb7f89-ff7d-4e0e-b803-5c06cebc1268"),
                            AboutCompany = "Backend solutions",
                            AddressId = new Guid("eb0bf179-2a90-42f2-a778-0457f10280b7"),
                            CompanyName = "CoreTech",
                            ContractType = "UOP",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c5bb0f28-a52d-4c3a-9fec-6e7eb50da633",
                            ImageId = new Guid("caa67e3a-d380-4a7f-9921-bce41d768349"),
                            JobLevel = "Lead",
                            OperationMode = "Onsite",
                            Requirements = "[\"Bachelor\\u0027s or Master\\u0027s degree in computer science/engineering or last year of university degree\",\" At least 7\\u002B years of hands-on Java development experience\",\" Very Good knowledge of Java (11\\u002B)\",\" Strong Experience with Spring Framework\",\" Strong Experience with JPA/Hibernate\",\" Strong Experience with SQL/NoSQL with understanding of database design and optimization methodologies\",\" Experience with Apache Camel\",\" Experience with Messaging Queues\",\" Experience with QueryDSL or other query mapping frameworks\",\" Experience in Angular 10\\u002B\",\" Knowledge of unit testing frameworks (preferred Cucumber)\",\" Good knowledge of linux commands and scripting\"]",
                            Responsibilities = "[\" Core Java development and Web applications with Spring and Angular\",\" Participate in requirements analysis\",\" Work with deployment pipelines and CI/CD processes\",\"Debugging and problem solving on existing applications\",\" Working in distributed teams with Agile Frameworks (Kanban/Scrum)\",\" Feature development, code reviews, guide our developers for best development practices\"]",
                            Salary = "15000-20000 zł brutto",
                            Technology = "Java",
                            Title = "Lead Backend Developer",
                            Type = "Backend",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("afab9186-1407-4601-8131-27f915c8f067"),
                            AboutCompany = "Web innovation hub",
                            AddressId = new Guid("61e53104-cc1e-4403-b781-ac2a9d90a675"),
                            CompanyName = "WebGen",
                            ContractType = "UOP",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "1ad681aa-e3d3-49b8-be8c-ce8fea3bd62d",
                            ImageId = new Guid("ba1c1bbf-cd15-49ce-8fcb-d744593c5299"),
                            JobLevel = "Junior",
                            OperationMode = "Remote",
                            Requirements = "[\"Experience with HTML, CSS, JavaScript\",\"Wykszta\\u0142cenie: min. student 3 roku - kierunek informatyka lub pokrewny\",\"Znajomo\\u015B\\u0107: Vue 3 \\u002B Angular \\u002B CSS \\u002B TypeScript\",\"Znajomo\\u015B\\u0107 system\\u00F3w kontroli wersji (Git)\",\"Znajomo\\u015B\\u0107 j\\u0119zyka angielskiego umo\\u017Cliwiaj\\u0105ca sprawn\\u0105 komunikacj\\u0119 w mowie i w pi\\u015Bmie\"]",
                            Responsibilities = "[\"Support web projects\",\"Projektowanie i implementowanie Front-endu na podstawie wymaga\\u0144 biznesowych\",\"Testowanie manualne oraz automatyczne dostarczanych rozwi\\u0105za\\u0144\",\"Udzia\\u0142 w pracach utrzymaniowych w \\u015Brodowiskach testowych i produkcyjnych\"]",
                            Salary = "4000-5000 zł brutto",
                            Technology = "Js",
                            Title = "Junior Fullstack Developer",
                            Type = "Fullstack",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4a57e566-7c4a-43a3-8412-706c4aa0c92e"),
                            AboutCompany = "Web solutions specialists",
                            AddressId = new Guid("6dceaa73-c28e-4aa5-b148-aa673e9b80b5"),
                            CompanyName = "App Builders",
                            ContractType = "B2B",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "1ad681aa-e3d3-49b8-be8c-ce8fea3bd62d",
                            ImageId = new Guid("0c97833d-79fb-43d9-a1e1-25032d81ad77"),
                            JobLevel = "Middle",
                            OperationMode = "Remote",
                            Requirements = "[\"3\\u002B years with JS \\u0026 Node\",\"Wykszta\\u0142cenie: min. student 3 roku - kierunek informatyka lub pokrewny\",\"Znajomo\\u015B\\u0107: Vue 3 \\u002B Angular \\u002B CSS \\u002B TypeScript\",\"Znajomo\\u015B\\u0107 system\\u00F3w kontroli wersji (Git)\",\"Znajomo\\u015B\\u0107 j\\u0119zyka angielskiego umo\\u017Cliwiaj\\u0105ca sprawn\\u0105 komunikacj\\u0119 w mowie i w pi\\u015Bmie\"]",
                            Responsibilities = "[\"Projektowanie i implementowanie Front-endu na podstawie wymaga\\u0144 biznesowych\",\"Testowanie manualne oraz automatyczne dostarczanych rozwi\\u0105za\\u0144\",\"Udzia\\u0142 w pracach utrzymaniowych w \\u015Brodowiskach testowych i produkcyjnych\"]",
                            Salary = "7000-9000 zł netto",
                            Technology = "Js",
                            Title = "Middle Fullstack Developer",
                            Type = "Fullstack",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("dca2e730-a65f-4351-a96f-6184ba993678"),
                            AboutCompany = "Comprehensive IT services",
                            AddressId = new Guid("aecc1bcc-91a9-406c-9258-b38bbd12fdb9"),
                            CompanyName = "DigitalCraft",
                            ContractType = "UOP",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "1ad681aa-e3d3-49b8-be8c-ce8fea3bd62d",
                            ImageId = new Guid("f884c7f8-502a-49a6-acde-7350a412b097"),
                            JobLevel = "Senior",
                            OperationMode = "Hybrid",
                            Requirements = "[\"5\\u002B years in fullstack dev, , Ruby on Rails, JavaScript\",\" dobra znajomo\\u015B\\u0107 zasad projektowania, dost\\u0119pno\\u015Bci i testowania u\\u017Cyteczno\\u015Bci\",\"znajomo\\u015B\\u0107 kompatybilno\\u015Bci mi\\u0119dzy przegl\\u0105darkami, techniki buforowania i optymalizacji wydajno\\u015Bci, znajomo\\u015B\\u0107 podstaw SEO i umiej\\u0119tno\\u015B\\u0107 optymalizacji pod k\\u0105tem wyszukiwarek\",\" aktywna wsp\\u00F3\\u0142praca z klientami oraz zespo\\u0142ami - Twoja wiedza pozwala na konstruktywny dialog i wyb\\u00F3r odpowiednich rozwi\\u0105za\\u0144.\",\" znajomo\\u015B\\u0107 systemu kontroli wersji (GIT)\"]",
                            Responsibilities = "[\" tworzenie portali turystycznych dla naszych Klient\\u00F3w w Polsce i za granic\\u0105\",\"  rozw\\u00F3j i tworzenie nowych funkcjonalno\\u015Bci dotychczasowych aplikacji\",\" uczestnictwo w przegl\\u0105dach kodu oraz d\\u0105\\u017Cenie do zapewnienia wysokiej jako\\u015Bci i efektywno\\u015Bci rozwi\\u0105za\\u0144\",\" aktywne uczestnictwo w tworzeniu specyfikacji projektowych wraz z zespo\\u0142em\"]",
                            Salary = "11000-14000 zł brutto",
                            Technology = "JavaScript",
                            Title = "Senior Fullstack Developer",
                            Type = "Fullstack",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f8a59eaf-8e24-40f4-a0a5-20b44a81e119"),
                            AboutCompany = "IT and web solutions",
                            AddressId = new Guid("d1977ab7-eef3-4def-ae48-66f65922b471"),
                            CompanyName = "Total Solutions",
                            ContractType = "UOP",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "1ad681aa-e3d3-49b8-be8c-ce8fea3bd62d",
                            ImageId = new Guid("01761843-a4d3-4dbd-988b-977094f0a083"),
                            JobLevel = "Lead",
                            OperationMode = "Remote",
                            Requirements = "[\"7\\u002B years in fullstack dev, JavaScript, Node.js, React\",\" Problem-solving skills and a proactive approach to challenges\",\" Experience working in a DevSecOps environment\",\" Solid understanding of change management processes\",\" Strong Gitlab, Jira, and Confluence experience for project and code management\",\"Knowledge of HTML, CSS, and JavaScript for front-end integration\",\"Ability to work collaboratively within a globally distributed team\"]",
                            Responsibilities = "[\"Lead fullstack projects\",\"Solid understanding of change management processes\",\" Strong Gitlab, Jira, and Confluence experience for project and code management\",\" Knowledge of HTML, CSS, and JavaScript for front-end integration\",\" Ability to work collaboratively within a globally distributed team\"]",
                            Salary = "16000-19000 zł brutto",
                            Technology = "Javascript",
                            Title = "Lead Fullstack Developer",
                            Type = "Fullstack",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("bd65092c-7896-4f1f-84f2-e5b246b60a43"),
                            AboutCompany = "Creative app developers",
                            AddressId = new Guid("bc05e016-1537-41f6-80b3-9bbf991dd39c"),
                            CompanyName = "AppLab",
                            ContractType = "B2B",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "b2cdded4-83f2-41da-ad9f-8feed8e0c300",
                            ImageId = new Guid("39fd3f9a-1911-4676-b4cf-d245f68a83a7"),
                            JobLevel = "Junior",
                            OperationMode = "Onsite",
                            Requirements = "[\"Basic knowledge in Swift, iOS\",\" Znajomo\\u015B\\u0107 Kotlin oraz Java\",\" Do\\u015Bwiadczenie z Android Studio\",\" znajomo\\u015B\\u0107 Git, Gerrit, Gradle\"]",
                            Responsibilities = "[\"Support mobile dev team\",\" Udzia\\u0142 w rozwoju oprogramowania aplikacji mobilnych dla bran\\u017Cy finansowej\",\" Stosowanie dobrych praktyk programowania obiektowego i wzorc\\u00F3w projektowych, takich jak MVP, MVVM czy MVC\",\" Implementacja atrakcyjnych i intuicyjnych interfejs\\u00F3w u\\u017Cytkownika\",\" \\u015Acis\\u0142a wsp\\u00F3\\u0142praca z zespo\\u0142em projektant\\u00F3w UX/UI, backendowc\\u00F3w, tester\\u00F3w oraz product manager\\u00F3w, aby spe\\u0142ni\\u0107 wymagania projektowe i dostarczy\\u0107 wysokiej jako\\u015Bci produkt\"]",
                            Salary = "7000-9000 zł netto",
                            Technology = "Swift",
                            Title = "Junior Mobile Developer",
                            Type = "Mobile",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("a3750fbd-7ec0-4372-b5e2-3335e92040db"),
                            AboutCompany = "Mobile app innovation",
                            AddressId = new Guid("a538082d-1000-4b50-b6ea-7e0f8b715c14"),
                            CompanyName = "NextGen Mobile",
                            ContractType = "B2B",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "b2cdded4-83f2-41da-ad9f-8feed8e0c300",
                            ImageId = new Guid("ba513f10-c72d-4cdb-a105-d6b462ec61fe"),
                            JobLevel = "Middle",
                            OperationMode = "Hybrid",
                            Requirements = "[\"2\\u002B years in mobile dev, Kotlin\",\"Znajomo\\u015B\\u0107 Kotlin oraz Java\",\" Do\\u015Bwiadczenie z Android Studio\",\"  znajomo\\u015B\\u0107 Git, Gerrit, Gradle\",\" Do\\u015Bwiadczene z Postman lub SoapUI\",\" Do\\u015Bwiadczenie z Jira, Confluence\",\" Do\\u015Bwiadczenie z Adobexd lub podobnymi bibliotekami\",\" Do\\u015Bwiadczenie z narz\\u0119dziami CI/CD (Jenkins)\"]",
                            Responsibilities = "[\"Maintain mobile apps\",\"Udzia\\u0142 w rozwoju oprogramowania aplikacji mobilnych dla bran\\u017Cy finansowej\",\"Stosowanie dobrych praktyk programowania obiektowego i wzorc\\u00F3w projektowych, takich jak MVP, MVVM czy MVC\",\"Implementacja atrakcyjnych i intuicyjnych interfejs\\u00F3w u\\u017Cytkownika\",\" \\u015Acis\\u0142a wsp\\u00F3\\u0142praca z zespo\\u0142em projektant\\u00F3w UX/UI, backendowc\\u00F3w, tester\\u00F3w oraz product manager\\u00F3w, aby spe\\u0142ni\\u0107 wymagania projektowe i dostarczy\\u0107 wysokiej jako\\u015Bci produkt\"]",
                            Salary = "10000-13000 zł netto",
                            Technology = "Kotlin",
                            Title = " Middle Mobile Developer",
                            Type = "Mobile",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("935476c5-cbd5-4feb-a60d-8493631241b4"),
                            AboutCompany = "Top mobile solutions",
                            AddressId = new Guid("3a55e504-11f1-4c82-8628-692982996558"),
                            CompanyName = "MobiSolutions",
                            ContractType = "UOP",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "b2cdded4-83f2-41da-ad9f-8feed8e0c300",
                            ImageId = new Guid("8b9cea71-52d1-46fd-b1e7-b2b54726bfa6"),
                            JobLevel = "Senior",
                            OperationMode = "Hybrid",
                            Requirements = "[\"5\\u002B years in mobile dev, , Android, Kotlin\",\" Advanced English (written and spoken)\",\" Expertise in software engineering toolchain (Jira, Git, CI/CD)\",\" Good communication skills\",\" Willingness to learn\",\" Basic know how of automotive problematics\"]",
                            Responsibilities = "[\"Design mobile features\",\" Programming languages  Swift\",\" Mobile development frameworks\",\" In-depth experience with application and user interface level using at least one mobile application development language\",\" Asynchronous programming and networking protocols\"]",
                            Salary = "15000-20000 zł brutto",
                            Technology = "Kotlin",
                            Title = "Senior Mobile Developer",
                            Type = "Mobile",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("7743fcad-08c3-479a-9db3-8b96ca933b82"),
                            AboutCompany = "Specializing in mobile tech",
                            AddressId = new Guid("9c654eec-ba66-40a6-8bf7-160591a9a602"),
                            CompanyName = "AppSphere",
                            ContractType = "UOP",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "b2cdded4-83f2-41da-ad9f-8feed8e0c300",
                            ImageId = new Guid("aa697543-3225-4e7b-8baf-83d71683b2c8"),
                            JobLevel = "Lead",
                            OperationMode = "Onsite",
                            Requirements = "[\"7\\u002B years in mobile dev, Swift\",\" Advanced English (written and spoken)\",\" Expertise in software engineering toolchain (Jira, Git, CI/CD)\",\"Good communication skills\",\" Willingness to learn\",\"Basic knowhow of automotive problematics\"]",
                            Responsibilities = "[\"Oversee mobile development\",\"Advanced English (written and spoken)\",\" Expertise in software engineering toolchain (Jira, Git, CI/CD)\",\"Good communication skills\",\" Willingness to learn\",\" Basic knowhow of automotive problematics\"]",
                            Salary = "20000-25000 zł brutto",
                            Technology = "Swift",
                            Title = "Lead Mobile Developer",
                            Type = "Mobile",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("252f07ea-9219-47b6-9e13-a09cfa17992e"),
                            AboutCompany = "Renowned in game dev",
                            AddressId = new Guid("6270749d-0b30-4e83-8374-12d23c22271a"),
                            CompanyName = "PlayMax Studios",
                            ContractType = "B2B",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "b2cdded4-83f2-41da-ad9f-8feed8e0c300",
                            ImageId = new Guid("32bafe62-e9ba-4c2a-9f2a-76053c689eff"),
                            JobLevel = "Junior",
                            OperationMode = "Remote",
                            Requirements = "[\"Experience with Unity, C#\"]",
                            Responsibilities = "[\"Write game mechanics code\"]",
                            Salary = "8000-9000 zł netto",
                            Technology = "C#",
                            Title = "Junior Game Developer",
                            Type = "GameDev",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("5a9037e0-132d-4457-8c3f-eae7d85cc54e"),
                            AboutCompany = "Innovators in gaming",
                            AddressId = new Guid("5f6ec67a-de91-4260-a1cf-50aebeb8181b"),
                            CompanyName = "GameForge",
                            ContractType = "UOP",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "1ad681aa-e3d3-49b8-be8c-ce8fea3bd62d",
                            ImageId = new Guid("a7bcaf46-c806-4bf4-825f-e17852cd276c"),
                            JobLevel = "Middle",
                            OperationMode = "Onsite",
                            Requirements = "[\"3\\u002B years with Unity,C#\"]",
                            Responsibilities = "[\"Create engaging game logic\"]",
                            Salary = "10000-12000 zł brutto",
                            Technology = "C#",
                            Title = "Middle Game Developer",
                            Type = "Gamedev",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("481b8480-85ab-4de6-8548-9c3aa90fc32f"),
                            AboutCompany = "A renowned leader in AAA game development",
                            AddressId = new Guid("868f8731-4a07-44fd-bd27-4acb4a35f77f"),
                            CompanyName = "PlayMax Studios",
                            ContractType = "UOP",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "f948c6b6-2651-4cf5-a4ae-a2046511989d",
                            ImageId = new Guid("20deaa5a-9243-4e3d-bed1-dc0a23aaccd3"),
                            JobLevel = "Senior",
                            OperationMode = "Remote",
                            Requirements = "[\" Programujesz w C\\u002B\\u002B 17\",\" Znasz STL, Git/Svn\",\"Posiadasz umiej\\u0119tno\\u015B\\u0107 analitycznego i logicznego my\\u015Blenia\",\"Masz zdolno\\u015B\\u0107 do analizy wymaga\\u0144 niezb\\u0119dnych do projektowania i wdra\\u017Cania najlepszych rozwi\\u0105za\\u0144\",\" Dysponujesz wiedz\\u0105 z zakresu zagadnie\\u0144 rachunku prawdopodobie\\u0144stwa, kombinatoryki i statystyki\",\" Microsoft Excel nie ma przed Tob\\u0105 tajemnic\",\" Komunikujesz si\\u0119 w j\\u0119zyku angielskim na poziomie komunikatywnym\"]",
                            Responsibilities = "[\"Develop complex game systems, mentor junior developers\",\" Nasz\\u0105 misj\\u0105 jest nie tylko wprowadzanie nowych tytu\\u0142\\u00F3w na rynek, ale tak\\u017Ce ich dostosowywanie do specyficznych wymaga\\u0144 r\\u00F3\\u017Cnych rynk\\u00F3w.\",\" Specjalizujemy si\\u0119 w zaawansowanej matematyce gier oraz tworzeniu i doskonaleniu mechanizm\\u00F3w kontrolnych.\"]",
                            Salary = "14000-17000 zł brutto",
                            Technology = "C#",
                            Title = "Senior Game Developer",
                            Type = "GameDev",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9aabffcc-702b-4460-b5e8-a629cb27b50e"),
                            AboutCompany = "Industry leader in immersive gaming experiences",
                            AddressId = new Guid("4b23304a-d75c-4dff-8b86-402a8656f39c"),
                            CompanyName = "Epic Games Studio",
                            ContractType = "UOP",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "c5bb0f28-a52d-4c3a-9fec-6e7eb50da633",
                            ImageId = new Guid("d86c3bf1-22f9-467a-bb25-a335508074c2"),
                            JobLevel = "Lead",
                            OperationMode = "Onsite",
                            Requirements = "[\"7\\u002B years in game development, experience leading large projects, Unreal Engine, C\\u002B\\u002B, Game Design\",\" Programujesz w C\\u002B\\u002B 17\",\" Znasz STL, Git/Svn\",\" Posiadasz umiej\\u0119tno\\u015B\\u0107 analitycznego i logicznego my\\u015Blenia\",\" Masz zdolno\\u015B\\u0107 do analizy wymaga\\u0144 niezb\\u0119dnych do projektowania i wdra\\u017Cania najlepszych rozwi\\u0105za\\u0144\",\" Dysponujesz wiedz\\u0105 z zakresu zagadnie\\u0144 rachunku prawdopodobie\\u0144stwa, kombinatoryki i statystyki\",\"Microsoft Excel nie ma przed Tob\\u0105 tajemnic\",\" Komunikujesz si\\u0119 w j\\u0119zyku angielskim na poziomie komunikatywnym\"]",
                            Responsibilities = "[\"Lead the game development team, oversee project lifecycle\",\"Nasz\\u0105 misj\\u0105 jest nie tylko wprowadzanie nowych tytu\\u0142\\u00F3w na rynek, ale tak\\u017Ce ich dostosowywanie do specyficznych wymaga\\u0144 r\\u00F3\\u017Cnych rynk\\u00F3w.\",\"Specjalizujemy si\\u0119 w zaawansowanej matematyce gier oraz tworzeniu i doskonaleniu mechanizm\\u00F3w kontrolnych.\"]",
                            Salary = "18000-20000 zł brutto",
                            Technology = "C++",
                            Title = "Lead Game Developer",
                            Type = "GameDev",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("JobHunt.Domain.Models.JobApplication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AboutInformation")
                        .HasColumnType("text")
                        .HasColumnName("about_information");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Cv")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cv");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_id");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("job_applications", (string)null);
                });

            modelBuilder.Entity("JobHunt.Domain.Models.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AddressId")
                        .HasColumnType("uuid")
                        .HasColumnName("address_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<Guid>("ImageId")
                        .HasColumnType("uuid")
                        .HasColumnName("image_id");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("ProfileSummary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("profile_summary");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("specialization");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.HasIndex("ImageId")
                        .IsUnique();

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("JobHunt.Domain.Models.University", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("EducationLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("education_level");

                    b.Property<string>("FieldOfStudy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_of_study");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("specialization");

                    b.Property<DateOnly>("StudyFrom")
                        .HasColumnType("date")
                        .HasColumnName("study_from");

                    b.Property<DateOnly>("StudyTo")
                        .HasColumnType("date")
                        .HasColumnName("study_to");

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("university_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.ToTable("universities", (string)null);
                });

            modelBuilder.Entity("JobHunt.Infrastructure.Identity.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Employer",
                            NormalizedName = "EMPLOYER"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("JobHunt.Domain.Models.Experience", b =>
                {
                    b.HasOne("JobHunt.Domain.Models.Profile", null)
                        .WithMany("Experiences")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunt.Domain.Models.Job", b =>
                {
                    b.HasOne("JobHunt.Domain.Models.Address", "Address")
                        .WithOne()
                        .HasForeignKey("JobHunt.Domain.Models.Job", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobHunt.Domain.Models.Image", "Image")
                        .WithOne()
                        .HasForeignKey("JobHunt.Domain.Models.Job", "ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("JobHunt.Domain.Models.JobApplication", b =>
                {
                    b.HasOne("JobHunt.Domain.Models.Job", "Job")
                        .WithMany("JobApplications")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("JobHunt.Domain.Models.Profile", b =>
                {
                    b.HasOne("JobHunt.Domain.Models.Address", "Address")
                        .WithOne()
                        .HasForeignKey("JobHunt.Domain.Models.Profile", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JobHunt.Domain.Models.Image", "Image")
                        .WithOne()
                        .HasForeignKey("JobHunt.Domain.Models.Profile", "ImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("JobHunt.Domain.Models.University", b =>
                {
                    b.HasOne("JobHunt.Domain.Models.Profile", null)
                        .WithMany("Universities")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("JobHunt.Domain.Models.Job", b =>
                {
                    b.Navigation("JobApplications");
                });

            modelBuilder.Entity("JobHunt.Domain.Models.Profile", b =>
                {
                    b.Navigation("Experiences");

                    b.Navigation("Universities");
                });
#pragma warning restore 612, 618
        }
    }
}
